name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.lock
          pip install -r requirements-dev.lock

      - name: Run formatting
        run: ruff format --check .

      - name: Run linting
        run: ruff check src/fastapi_image

      - name: Run tests
        run: python -m pytest
